services:
  - type: web
    name: smarthire-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://smarthire-ai-job-portal.onrender.com/api
